<?php

/**
 * hook_form_alter().
 * Used to add placeholder to search.
 */
function whc_form_search_block_form_alter(&$form, &$form_state) {
  $form['keys']['#attributes']['placeholder'][] = t('Search');
}

function whc_preprocess_views_view(&$variables) {
  $view = $variables['view'];

  $variables['title'] = [
    '#markup' => $view->getTitle(),
  ];
}


function whc_preprocess_html(&$variables) {
  if (isset($variables['node_type'])) {
    // Add node-TYPE class to the <body> element.
    $variables['attributes']['class'][] = 'node-' . $variables['node_type'];
  }
}